deployments:
  deploymentGating:
    enabled: true
    retry: 2
    sleep: 3
    environments: 
    - Development
    - Production
    - ::::development-ス
    - 111:test_staging-env
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS9iYjZjNzViYS1kYWNkLTExZWUtODU1ZC0wYWJlM2Y0YTY2MDE=
