deployments:
  deploymentGating:
    enabled: true
    retry: 20
    sleep: 180
    environments: 
    - Development
    - Production
    - ::::development-ス
    - 111:test_staging-env
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS8zY2M3Njc1OC1iYzFjLTExZWUtYjY3ZC0wYWJlM2Y0YTY2MDE=
