deployments:
  deploymentGating:
    enabled: true
    environments: 
    - development
    - production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzQzYWU2ZWRlLTRkMjctNGIwOC1hOTA0LWE5MjJmYTU5NmNhYi8zMjU3OTFkMi05OWE2LTExZWUtYjBlZi0wYWJlM2Y0YTY2MDE=
    - test
