deployments:
  services:
    checkGatingStatus:
      environmentId: Development
      sleep: 60
      retry: 5
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzhiZjE1N2E5LTA2NzgtNDI0YS1iYjMwLTE3NjU3OTUyYjVkMy85YzI0YWU3Mi00M2RjLTExZWQtYmZhYy0wZTNlN2EyMWE5MTE=
    - test
