deployments:
  services:
    deploymentGating:
      enabled: true
      environments: 
      - Development
      - Production
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzhiZjE1N2E5LTA2NzgtNDI0YS1iYjMwLTE3NjU3OTUyYjVkMy8zNDY0MjI0Mi1hZTFlLTExZWUtYTNiYi0wZTNlN2EyMWE5MTE=
